// Copyright (c) OpenMetadata Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/codegen/generate.py; DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/rsantos1089/terraform-provider-openmetadata/internal/client"
)

var _ resource.Resource = &PolicyResource{}
var _ resource.ResourceWithImportState = &PolicyResource{}

const policyCollection = "policies"

type PolicyResource struct {
	client *client.Client
}

type PolicyResourceModel struct {
	ID  types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	DisplayName types.String `tfsdk:"display_name"`
	Description types.String `tfsdk:"description"`
	Owners types.List `tfsdk:"owners"`
	Rules types.String `tfsdk:"rules"`
	Enabled types.Bool `tfsdk:"enabled"`
	Location types.String `tfsdk:"location"`
	Domains types.List `tfsdk:"domains"`
	FQN types.String `tfsdk:"fully_qualified_name"`
}

func NewPolicyResource() resource.Resource {
	return &PolicyResource{}
}

func (r *PolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_policy"
}

func (r *PolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages an OpenMetadata Policy.",
		Attributes: map[string]schema.Attribute{
			"id":                   IDAttribute(),
			"name":         NameAttribute(),
			"display_name": DisplayNameAttribute(),
			"description":  DescriptionAttribute(false),
			"owners":  OwnersAttribute(),
			"rules": schema.StringAttribute{
				Description: "Policy rules as a JSON array string. At least one rule is required. " +
					"The value is sent to the API on create/update but is not read back (the API may " +
					"reorder JSON fields). Supply the exact JSON you want stored in Terraform state.",
				Required: true,
			},
			"enabled": schema.BoolAttribute{
				Description: "Is the policy enabled.",
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(true),
			},
			"location": schema.StringAttribute{
				Description: "UUID of Location where this policy is applied",
				Optional: true,
				Computed: true,
			},
			"domains": DomainsAttribute(),
			"fully_qualified_name": FullyQualifiedNameAttribute(),
		},
	}
}

func (r *PolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data type", fmt.Sprintf("Expected *client.Client, got: %T", req.ProviderData))
		return
	}
	r.client = c
}

func (r *PolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan PolicyResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, err := r.buildBody(ctx, &plan)
	if err != nil {
		resp.Diagnostics.AddError("Invalid policy configuration", err.Error())
		return
	}
	raw, err := r.client.CreateOrUpdate(ctx, policyCollection, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating policy", err.Error())
		return
	}

	r.readIntoState(raw, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *PolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state PolicyResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	raw, err := r.client.GetByName(ctx, policyCollection, state.Name.ValueString(), []string{"owners", "domains"})
	if err != nil {
		resp.Diagnostics.AddError("Error reading policy", err.Error())
		return
	}
	if raw == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	r.readIntoState(raw, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *PolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan PolicyResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, err := r.buildBody(ctx, &plan)
	if err != nil {
		resp.Diagnostics.AddError("Invalid policy configuration", err.Error())
		return
	}
	raw, err := r.client.CreateOrUpdate(ctx, policyCollection, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating policy", err.Error())
		return
	}

	r.readIntoState(raw, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *PolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state PolicyResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Info(ctx, "Deleting policy", map[string]interface{}{"name": state.Name.ValueString()})
	if err := r.client.Delete(ctx, policyCollection, state.ID.ValueString(), true); err != nil {
		resp.Diagnostics.AddError("Error deleting policy", err.Error())
	}
}

func (r *PolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	raw, err := r.client.GetByName(ctx, policyCollection, req.ID, []string{"owners", "domains"})
	if err != nil {
		resp.Diagnostics.AddError("Error importing policy", err.Error())
		return
	}
	if raw == nil {
		resp.Diagnostics.AddError("Policy not found", fmt.Sprintf("No policy with name %q", req.ID))
		return
	}
	var state PolicyResourceModel
	r.readIntoState(raw, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *PolicyResource) buildBody(ctx context.Context, plan *PolicyResourceModel) (map[string]interface{}, error) {
	body := map[string]interface{}{
		"name": plan.Name.ValueString(),
	}
	// rules must be sent as a JSON array, not a raw string.
	var rules interface{}
	if err := json.Unmarshal([]byte(plan.Rules.ValueString()), &rules); err != nil {
		return nil, fmt.Errorf("invalid rules JSON: %w", err)
	}
	body["rules"] = rules
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		body["description"] = plan.Description.ValueString()
	}
	if !plan.DisplayName.IsNull() && !plan.DisplayName.IsUnknown() {
		body["displayName"] = plan.DisplayName.ValueString()
	}
	if !plan.Owners.IsNull() && !plan.Owners.IsUnknown() {
		body["owners"] = extractOwnerRefs(ctx, plan.Owners)
	}
	if !plan.Enabled.IsNull() && !plan.Enabled.IsUnknown() {
		body["enabled"] = plan.Enabled.ValueBool()
	}
	if !plan.Location.IsNull() && !plan.Location.IsUnknown() {
		body["location"] = plan.Location.ValueString()
	}
	if !plan.Domains.IsNull() && !plan.Domains.IsUnknown() {
		var vals []string
		plan.Domains.ElementsAs(ctx, &vals, false)
		body["domains"] = vals
	}
	return body, nil
}

func (r *PolicyResource) readIntoState(raw []byte, state *PolicyResourceModel) {
	data, err := Unmarshal(raw)
	if err != nil {
		return
	}
	state.ID = StringVal(data, "id")
	state.Name = StringVal(data, "name")
	state.DisplayName = StringVal(data, "displayName")
	state.Description = StringVal(data, "description")
	// rules is intentionally NOT read back from the API response. The API may
	// reorder JSON fields, producing a string that differs from what the user
	// wrote. Treating rules as write-only (like connection_json in database
	// services) keeps state stable. For import, rules is excluded via
	// ImportStateVerifyIgnore.
	state.Enabled = BoolVal(data, "enabled")
	state.Location = StringVal(data, "location")
	state.FQN = StringVal(data, "fullyQualifiedName")
	state.Domains = StringListVal(data, "domains")
	state.Owners = OwnersListNull()
}
