// Copyright (c) OpenMetadata Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/codegen/generate.py; DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/rsantos1089/terraform-provider-openmetadata/internal/client"
)

var _ resource.Resource = &RoleResource{}
var _ resource.ResourceWithImportState = &RoleResource{}

const roleCollection = "roles"

type RoleResource struct {
	client *client.Client
}

type RoleResourceModel struct {
	ID  types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	DisplayName types.String `tfsdk:"display_name"`
	Description types.String `tfsdk:"description"`
	Policies types.List `tfsdk:"policies"`
	Domains types.List `tfsdk:"domains"`
	FQN types.String `tfsdk:"fully_qualified_name"`
}

func NewRoleResource() resource.Resource {
	return &RoleResource{}
}

func (r *RoleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_role"
}

func (r *RoleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages an OpenMetadata Role.",
		Attributes: map[string]schema.Attribute{
			"id":                   IDAttribute(),
			"name":         NameAttribute(),
			"display_name": DisplayNameAttribute(),
			"description":  DescriptionAttribute(false),
			"policies": schema.ListAttribute{
				Description: "Policies that is attached to this role. At least one policy is required.",
				Required: true,
				ElementType: types.StringType,
			},
			"domains": DomainsAttribute(),
			"fully_qualified_name": FullyQualifiedNameAttribute(),
		},
	}
}

func (r *RoleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data type", fmt.Sprintf("Expected *client.Client, got: %T", req.ProviderData))
		return
	}
	r.client = c
}

func (r *RoleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan RoleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := r.buildBody(ctx, &plan)
	raw, err := r.client.CreateOrUpdate(ctx, roleCollection, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating role", err.Error())
		return
	}

	r.readIntoState(raw, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *RoleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state RoleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	raw, err := r.client.GetByName(ctx, roleCollection, state.Name.ValueString(), []string{"domains", "policies"})
	if err != nil {
		resp.Diagnostics.AddError("Error reading role", err.Error())
		return
	}
	if raw == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	r.readIntoState(raw, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *RoleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan RoleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := r.buildBody(ctx, &plan)
	raw, err := r.client.CreateOrUpdate(ctx, roleCollection, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating role", err.Error())
		return
	}

	r.readIntoState(raw, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *RoleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state RoleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Info(ctx, "Deleting role", map[string]interface{}{"name": state.Name.ValueString()})
	if err := r.client.Delete(ctx, roleCollection, state.ID.ValueString(), true); err != nil {
		resp.Diagnostics.AddError("Error deleting role", err.Error())
	}
}

func (r *RoleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	raw, err := r.client.GetByName(ctx, roleCollection, req.ID, []string{"domains", "policies"})
	if err != nil {
		resp.Diagnostics.AddError("Error importing role", err.Error())
		return
	}
	if raw == nil {
		resp.Diagnostics.AddError("Role not found", fmt.Sprintf("No role with name %q", req.ID))
		return
	}
	var state RoleResourceModel
	r.readIntoState(raw, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *RoleResource) buildBody(ctx context.Context, plan *RoleResourceModel) map[string]interface{} {
	body := map[string]interface{}{
		"name": plan.Name.ValueString(),
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		body["description"] = plan.Description.ValueString()
	}
	if !plan.DisplayName.IsNull() && !plan.DisplayName.IsUnknown() {
		body["displayName"] = plan.DisplayName.ValueString()
	}
	if !plan.Policies.IsNull() && !plan.Policies.IsUnknown() {
		var vals []string
		plan.Policies.ElementsAs(ctx, &vals, false)
		body["policies"] = vals
	}
	if !plan.Domains.IsNull() && !plan.Domains.IsUnknown() {
		var vals []string
		plan.Domains.ElementsAs(ctx, &vals, false)
		body["domains"] = vals
	}
	return body
}

func (r *RoleResource) readIntoState(raw []byte, state *RoleResourceModel) {
	data, err := Unmarshal(raw)
	if err != nil {
		return
	}
	state.ID = StringVal(data, "id")
	state.Name = StringVal(data, "name")
	state.DisplayName = StringVal(data, "displayName")
	state.Description = StringVal(data, "description")
	state.Policies = StringListVal(data, "policies")
	state.Domains = StringListVal(data, "domains")
	state.FQN = StringVal(data, "fullyQualifiedName")
}
